In [1]:
import pandas as pd
import numpy as np

In [2]:
results_session = pd.read_csv("./da_particles_cross_session.csv")

### Cross Session

In [3]:
results_session

,Unnamed: 0,align,no_align,time,distance,n_proj,n_epochs,seed,subject,target_subject,multifreq,reg,cross_subject
0,0,0.832740,0.822064,14.002963,les,500,500,2473,1,0,False,10.0,False
1,1,0.832740,0.822064,14.002963,les,500,500,2473,1,0,False,10.0,False
2,2,0.832740,0.822064,14.002963,les,500,500,2473,1,0,False,10.0,False
3,3,0.832740,0.822064,14.002963,les,500,500,2473,1,0,False,10.0,False
4,4,0.832740,0.822064,14.002963,les,500,500,2473,1,0,False,10.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,495,0.806818,0.757576,3.511983,logsw,500,500,929,9,0,False,1.0,False
496,496,0.806818,0.757576,3.511983,logsw,500,500,929,9,0,False,1.0,False
497,497,0.806818,0.757576,3.511983,logsw,500,500,929,9,0,False,1.0,False
498,498,0.806818,0.757576,3.511983,logsw,500,500,929,9,0,False,1.0,False
499,499,0.806818,0.757576,3.511983,logsw,500,500,929,9,0,False,1.0,False

In [4]:
distances = results_session["distance"].unique()
subjects = results_session["subject"].unique()

In [14]:
n_epochs = 500

L_session = {}
for distance in distances:
    L_session[distance] = {}
L_session["no_align"] = {}


for distance in distances:
    for s in subjects:
        dico_distances = {"mean_score": 0, "std_score": 0, "mean_time": 0, "std_time":0}

        scores = results_session[
            (results_session["distance"] == distance)
            & (results_session["subject"] == s)
            & (results_session["n_epochs"] == n_epochs)
        ]["align"]
        m_score = scores.mean()
        std_score = scores.std()
        
        times = results_session[
            (results_session["distance"] == distance)
            & (results_session["subject"] == s)
            & (results_session["n_epochs"] == n_epochs)
        ]["time"]
        m_t = times.mean()
        std_t = times.std()
        
        dico_distances["mean_score"] = m_score
        dico_distances["std_score"] = std_score
        dico_distances["mean_time"] = m_t
        dico_distances["std_time"] = std_t
        
        L_session[distance][s] = dico_distances
        
        
for s in subjects:
    dico_distances = {"mean_score": 0, "std_score": 0, "mean_time": 0, "std_time":0}

    scores = results_session[
        (results_session["distance"] == distance)
        & (results_session["subject"] == s)
        & (results_session["n_epochs"] == n_epochs)
    ]["no_align"]
    m_score = scores.mean()
    std_score = scores.std()

    dico_distances["mean_score"] = m_score
    dico_distances["std_score"] = std_score

    L_session["no_align"][s] = dico_distances

In [16]:
acc_session = np.zeros((len(subjects), len(distances)+1))
acc_std_session = np.zeros((len(subjects), len(distances)))
t_session = np.zeros((len(subjects), len(distances)))
t_std_session = np.zeros((len(subjects), len(distances)))

for i, distance in enumerate(distances):
    for j, s in enumerate(subjects):
        acc_session[j, i] = L_session[distance][s]["mean_score"]
        acc_std_session[j, i] = L_session[distance][s]["std_score"]
        t_session[j, i] = L_session[distance][s]["mean_time"]
        t_std_session[j, i] = L_session[distance][s]["std_time"]
        
distance = "no_align"        
for j, s in enumerate(subjects):
    acc_session[j, -1] = L_session[distance][s]["mean_score"]

In [17]:
print("Accuracy Cross Session + Particles")
pd.DataFrame(acc_session, index=subjects, columns=np.concatenate([distances, ["no_align"]]))

Accuracy Cross Session + Particles

        les       lew     spdsw     logsw  no_align
1  0.829181  0.779359  0.851957  0.851957  0.822064
3  0.814652  0.824176  0.871062  0.863736  0.798535
7  0.732852  0.790614  0.818051  0.817329  0.722022
8  0.850185  0.800738  0.841328  0.833210  0.793358
9  0.704545  0.761364  0.803030  0.790152  0.757576

In [18]:
pd.DataFrame(acc_session, index=subjects, columns=np.concatenate([distances, ["no_align"]])).mean(axis=0)

les         0.786283
lew         0.791250
spdsw       0.837086
logsw       0.831277
no_align    0.778711
dtype: float64

In [19]:
pd.DataFrame(acc_session, index=subjects, columns=np.concatenate([distances, ["no_align"]])).std(axis=0)

les         0.063766
lew         0.023501
spdsw       0.026999
logsw       0.029030
no_align    0.039203
dtype: float64

In [20]:
print("Runtime Cross Session + Particles")
pd.DataFrame(t_session, index=subjects, columns=distances)

Runtime Cross Session + Particles

         les       lew     spdsw     logsw
1  10.953869  8.811712  3.747367  3.757061
3  10.448567  8.472196  3.728346  3.702158
7  10.091328  8.867609  3.749185  3.705466
8  10.284881  8.599272  3.687343  3.669792
9  15.384095  7.772284  3.507221  3.492597

In [21]:
pd.DataFrame(t_session, index=subjects, columns=distances).mean(axis=0)

les      11.432548
lew       8.504614
spdsw     3.683892
logsw     3.665415
dtype: float64

In [22]:
pd.DataFrame(t_session, index=subjects, columns=distances).std(axis=0)

les      2.232044
lew      0.439430
spdsw    0.101849
logsw    0.101536
dtype: float64

### Cross Subjects

In [23]:
results_subject = pd.read_csv("./da_particles_cross_subject.csv")

In [24]:
results_subject

,Unnamed: 0,align,no_align,time,distance,n_proj,n_epochs,seed,subject,target_subject,multifreq,reg,cross_subject
0,0,1.000000,1.000000,0.000000,les,500,500,2473,1,1,False,10.0,True
1,1,0.759259,0.522222,14.217470,les,500,500,2473,1,3,False,10.0,True
2,2,0.594096,0.505535,11.290337,les,500,500,2473,1,7,False,10.0,True
3,3,0.700758,0.390152,9.099653,les,500,500,2473,1,8,False,10.0,True
4,4,0.468354,0.265823,10.021838,les,500,500,2473,1,9,False,10.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,495,0.542125,0.267399,3.511295,logsw,500,500,929,9,1,False,1.0,True
496,496,0.562963,0.285185,3.522498,logsw,500,500,929,9,3,False,1.0,True
497,497,0.487085,0.247232,3.499616,logsw,500,500,929,9,7,False,1.0,True
498,498,0.587121,0.397727,3.511898,logsw,500,500,929,9,8,False,1.0,True
499,499,1.000000,1.000000,0.000000,logsw,500,500,929,9,9,False,1.0,True

In [25]:
distances = results_subject["distance"].unique()
subjects_src = results_subject["subject"].unique()
subjects_tgt = results_subject["target_subject"].unique()

In [35]:
n_epochs = 500 # 250

L_subject = {}
for distance in distances:
    L_subject[distance] = {}
L_subject["no_align"] = {}


for distance in distances:
    for s1 in subjects_src:
        L_subject[distance][s1] = {}
        for s2 in subjects_tgt:
            if s1 != s2:
                L_subject[distance][s1][s2] = {}
        
                scores = results_subject[
                    (results_subject["distance"] == distance)
                    & (results_subject["subject"] == s1)
                    & (results_subject["target_subject"] == s2)
                    & (results_subject["n_epochs"] == n_epochs) 
                ]["align"]
                m_score = scores.mean()
                std_score = scores.std()
                
                times = results_subject[
                    (results_subject["distance"] == distance)
                    & (results_subject["subject"] == s1)
                    & (results_subject["target_subject"] == s2)
                    & (results_subject["n_epochs"] == n_epochs)
                ]["time"]
                
                m_t = times.mean()
                std_t = times.std()
                
                L_subject[distance][s1][s2]["mean_score"] = m_score
                L_subject[distance][s1][s2]["std_score"] = std_score
                L_subject[distance][s1][s2]["mean_time"] = m_t
                L_subject[distance][s1][s2]["std_t"] = std_t
        
        
for s1 in subjects_src:
    L_subject["no_align"][s1] = {}
    for s2 in subjects_tgt:
        if s1 != s2:
            dico_distances = {"mean_score": 0, "std_score": 0, "mean_time": 0, "std_time":0}

            scores = results_subject[
                (results_subject["distance"] == distance)
                & (results_subject["subject"] == s1)
                & (results_subject["target_subject"] == s2)
                & (results_subject["n_epochs"] == n_epochs)
            ]["no_align"]
            m_score = scores.mean()
            std_score = scores.std()

            dico_distances["mean_score"] = m_score
            dico_distances["std_score"] = std_score

            L_subject["no_align"][s1][s2] = dico_distances

In [37]:
results_mean = np.zeros((len(subjects_src), len(distances)+1))
t_subjects = np.zeros((len(subjects_src), len(distances)))

for l, distance in enumerate(L_subject):
    results = np.zeros((5,5))
    ts = np.zeros((5,5))
    for i, s1 in enumerate(subjects_src):
        for j, s2 in enumerate(subjects_tgt):
            if s1 != s2:
                results[i, j] = L_subject[distance][s1][s2]["mean_score"]
                if distance != "no_align":
                    ts[i, j] = L_subject[distance][s1][s2]["mean_time"]
                
        results_mean[i, l] = np.sum(results[i, :])/4
        
        if distance != "no_align":
            t_subjects[i, l] = np.sum(ts[i, :])/4
                       
    results_pd = pd.DataFrame(results, index=subjects_src, columns=subjects_tgt)
    print(distance)
    print(results_pd)
    print()

les
          1         3         7         8         9
1  0.000000  0.740741  0.592620  0.710606  0.486076
3  0.654212  0.000000  0.656827  0.680303  0.540084
7  0.586081  0.684444  0.000000  0.587879  0.522363
8  0.622711  0.686667  0.610332  0.000000  0.551055
9  0.595604  0.714815  0.565314  0.720455  0.000000

lew
          1         3         7         8         9
1  0.000000  0.725926  0.554244  0.693182  0.540084
3  0.633700  0.000000  0.619926  0.621212  0.535865
7  0.501832  0.629630  0.000000  0.481061  0.514768
8  0.615385  0.740741  0.538745  0.000000  0.572152
9  0.483516  0.633333  0.571956  0.640152  0.000000

spdsw
          1         3         7         8         9
1  0.000000  0.690370  0.608856  0.681818  0.521519
3  0.662271  0.000000  0.701845  0.708333  0.556962
7  0.580220  0.710370  0.000000  0.618182  0.529958
8  0.577289  0.704444  0.581550  0.000000  0.574684
9  0.552381  0.618519  0.521033  0.656818  0.000000

logsw
          1         3         7         8         9
1  0.000000  0.697037  0.614022  0.675758  0.489451
3  0.675458  0.000000  0.659779  0.712121  0.551055
7  0.567766  0.674815  0.000000  0.593182  0.503797
8  0.610256  0.697037  0.546863  0.000000  0.545992
9  0.542125  0.600000  0.472325  0.581818  0.000000

no_align
          1         3         7         8         9
1  0.000000  0.522222  0.505535  0.390152  0.265823
3  0.344322  0.000000  0.309963  0.496212  0.274262
7  0.520147  0.533333  0.000000  0.261364  0.265823
8  0.498168  0.577778  0.243542  0.000000  0.396624
9  0.267399  0.285185  0.247232  0.395455  0.000000

In [38]:
print("Mean Accuracy Cross Subject + Particles")
pd.DataFrame(results_mean, index=subjects_src, columns=np.concatenate([distances, ["no_align"]]))

Mean Accuracy Cross Subject + Particles

        les       lew     spdsw     logsw  no_align
1  0.632511  0.628359  0.625641  0.619067  0.420933
3  0.632857  0.602676  0.657353  0.649603  0.356190
7  0.595192  0.531822  0.609682  0.584890  0.395167
8  0.617691  0.616756  0.609492  0.600037  0.429028
9  0.649047  0.582239  0.587188  0.549067  0.298818

In [39]:
pd.DataFrame(results_mean, index=subjects_src, columns=np.concatenate([distances, ["no_align"]])).mean(axis=0)

les         0.625459
lew         0.592370
spdsw       0.617871
logsw       0.600533
no_align    0.380027
dtype: float64

In [40]:
pd.DataFrame(results_mean, index=subjects_src, columns=np.concatenate([distances, ["no_align"]])).std(axis=0)

les         0.020232
lew         0.037963
spdsw       0.025971
logsw       0.037567
no_align    0.053541
dtype: float64

In [41]:
print("Runtime Cross Subject + Particles")
pd.DataFrame(t_subjects, index=subjects_src, columns=distances)

Runtime Cross Subject + Particles

         les        lew     spdsw     logsw
1  10.425320   8.836961  3.718065  3.696231
3  10.379532  11.019561  3.695966  3.674692
7  10.288147  10.083615  3.720189  3.686658
8  10.477075   8.901887  3.678466  3.651529
9  10.053241   8.867770  3.538886  3.513674

In [42]:
pd.DataFrame(t_subjects, index=subjects_src, columns=distances).mean(axis=0)

les      10.324663
lew       9.541959
spdsw     3.670314
logsw     3.644557
dtype: float64

In [43]:
pd.DataFrame(t_subjects, index=subjects_src, columns=distances).std(axis=0)

les      0.166865
lew      0.979533
spdsw    0.075441
logsw    0.075049
dtype: float64