In [1]:
import pandas as pd
import numpy as np

In [2]:
results_session = pd.read_csv("./da_particles_session.csv")
results_subject = pd.read_csv("./da_particles_subject.csv")

### Cross Session

In [3]:
results_session

,Unnamed: 0,align,no_align,time,distance,n_proj,n_epochs,seed,subject,target_subject,cross_subject,multifreq
0,0,0.790036,0.775801,2.925475,lew,500,50,2473,1,0,False,False
1,1,0.790036,0.775801,2.925475,lew,500,50,2473,1,0,False,False
2,2,0.790036,0.775801,2.925475,lew,500,50,2473,1,0,False,False
3,3,0.790036,0.775801,2.925475,lew,500,50,2473,1,0,False,False
4,4,0.790036,0.775801,2.925475,lew,500,50,2473,1,0,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
370,370,0.719697,0.768939,0.708058,spdsw,500,50,929,9,0,False,False
371,371,0.719697,0.768939,0.708058,spdsw,500,50,929,9,0,False,False
372,372,0.719697,0.768939,0.708058,spdsw,500,50,929,9,0,False,False
373,373,0.719697,0.768939,0.708058,spdsw,500,50,929,9,0,False,False
374,374,0.719697,0.768939,0.708058,spdsw,500,50,929,9,0,False,False

In [4]:
distances = results_session["distance"].unique()
subjects = results_session["subject"].unique()

In [5]:
L_session = {}
for distance in distances:
    L_session[distance] = {}
L_session["no_align"] = {}


for distance in distances:
    for s in subjects:
        dico_distances = {"mean_score": 0, "std_score": 0, "mean_time": 0, "std_time":0}

        scores = results_session[
            (results_session["distance"] == distance)
            & (results_session["subject"] == s)
        ]["align"]
        m_score = scores.mean()
        std_score = scores.std()
        
        times = results_session[
            (results_session["distance"] == distance)
            & (results_session["subject"] == s)
        ]["time"]
        m_t = times.mean()
        std_t = times.std()
        
        dico_distances["mean_score"] = m_score
        dico_distances["std_score"] = std_score
        dico_distances["mean_time"] = m_t
        dico_distances["std_time"] = std_t
        
        L_session[distance][s] = dico_distances
        
        
for s in subjects:
    dico_distances = {"mean_score": 0, "std_score": 0, "mean_time": 0, "std_time":0}

    scores = results_session[
        (results_session["distance"] == distance)
        & (results_session["subject"] == s)
    ]["no_align"]
    m_score = scores.mean()
    std_score = scores.std()

    dico_distances["mean_score"] = m_score
    dico_distances["std_score"] = std_score

    L_session["no_align"][s] = dico_distances

In [6]:
L_session

{'lew': {1: {'mean_score': 0.7900355871886121,
   'std_score': 0.0,
   'mean_time': 1.456824541091919,
   'std_time': 0.7494925577983949},
  3: {'mean_score': 0.805860805860806,
   'std_score': 1.1331166295920987e-16,
   'mean_time': 1.0826532363891601,
   'std_time': 0.0037806937017992575},
  7: {'mean_score': 0.7234657039711191,
   'std_score': 0.010316743802335899,
   'mean_time': 1.1383656024932862,
   'std_time': 0.005014249097237098},
  8: {'mean_score': 0.8228782287822878,
   'std_score': 0.0,
   'mean_time': 1.1160211563110352,
   'std_time': 0.004545856185579294},
  9: {'mean_score': 0.7803030303030303,
   'std_score': 0.0,
   'mean_time': 0.9910544395446778,
   'std_time': 0.0063964893662383044}},
 'les': {1: {'mean_score': 0.7686832740213522,
   'std_score': 1.1331166295920987e-16,
   'mean_time': 2.321163463592529,
   'std_time': 0.38319704239497354},
  3: {'mean_score': 0.816849816849817,
   'std_score': 1.1331166295920987e-16,
   'mean_time': 2.0962663173675535,
   'std_time': 0.41557531221442084},
  7: {'mean_score': 0.7617328519855594,
   'std_score': 1.1331166295920987e-16,
   'mean_time': 1.689553689956665,
   'std_time': 0.17189294260410823},
  8: {'mean_score': 0.8154981549815499,
   'std_score': 1.1331166295920987e-16,
   'mean_time': 2.0282185077667236,
   'std_time': 0.3591613604335508},
  9: {'mean_score': 0.6628787878787878,
   'std_score': 0.0064690345744694375,
   'mean_time': 3.5039531230926513,
   'std_time': 0.31718072762860855}},
 'spdsw': {1: {'mean_score': 0.7935943060498221,
   'std_score': 0.011016711518983814,
   'mean_time': 0.7392431735992432,
   'std_time': 0.0012975572275324841},
  3: {'mean_score': 0.8278388278388279,
   'std_score': 0.007842022331297419,
   'mean_time': 0.7382388591766358,
   'std_time': 0.004146324062586999},
  7: {'mean_score': 0.7545126353790614,
   'std_score': 0.003295562921210382,
   'mean_time': 0.7360356330871582,
   'std_time': 0.0026524100116108906},
  8: {'mean_score': 0.8509225092250923,
   'std_score': 0.0018450184501844766,
   'mean_time': 0.7387770652770996,
   'std_time': 0.0019990943300439777},
  9: {'mean_score': 0.7598484848484849,
   'std_score': 0.029197805757189815,
   'mean_time': 0.7066250801086426,
   'std_time': 0.0027100065204273657}},
 'no_align': {1: {'mean_score': 0.7758007117437722,
   'std_score': 0.0,
   'mean_time': 0,
   'std_time': 0},
  3: {'mean_score': 0.7655677655677655,
   'std_score': 0.0,
   'mean_time': 0,
   'std_time': 0},
  7: {'mean_score': 0.7227436823104694,
   'std_score': 0.0014738205431908168,
   'mean_time': 0,
   'std_time': 0},
  8: {'mean_score': 0.7586715867158672,
   'std_score': 0.00301290251264844,
   'mean_time': 0,
   'std_time': 0},
  9: {'mean_score': 0.7674242424242423,
   'std_score': 0.005244080721539184,
   'mean_time': 0,
   'std_time': 0}}}

In [7]:
acc_session = np.zeros((len(subjects), len(distances)+1))
t_session = np.zeros((len(subjects), len(distances)))

for i, distance in enumerate(distances):
    for j, s in enumerate(subjects):
        acc_session[j, i] = L_session[distance][s]["mean_score"]
        t_session[j, i] = L_session[distance][s]["mean_time"]
        
distance = "no_align"        
for j, s in enumerate(subjects):
    acc_session[j, -1] = L_session[distance][s]["mean_score"]

In [8]:
pd.DataFrame(acc_session, index=subjects, columns=np.concatenate([distances, ["no_align"]]))

        lew       les     spdsw  no_align
1  0.790036  0.768683  0.793594  0.775801
3  0.805861  0.816850  0.827839  0.765568
7  0.723466  0.761733  0.754513  0.722744
8  0.822878  0.815498  0.850923  0.758672
9  0.780303  0.662879  0.759848  0.767424

In [9]:
pd.DataFrame(t_session, index=subjects, columns=distances)

        lew       les     spdsw
1  1.456825  2.321163  0.739243
3  1.082653  2.096266  0.738239
7  1.138366  1.689554  0.736036
8  1.116021  2.028219  0.738777
9  0.991054  3.503953  0.706625

### Cross Subjects

In [10]:
results_subject

,Unnamed: 0,align,no_align,time,distance,n_proj,n_epochs,seed,subject,target_subject,cross_subject,multifreq
0,0,1.000000,1.000000,0.000000,lew,500,150,2473,1,1,True,False
1,1,0.655556,0.507407,4.933199,lew,500,150,2473,1,3,True,False
2,2,0.409594,0.420664,3.139446,lew,500,150,2473,1,7,True,False
3,3,0.560606,0.356061,3.445276,lew,500,150,2473,1,8,True,False
4,4,0.388186,0.261603,3.430490,lew,500,150,2473,1,9,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
370,370,0.428571,0.256410,2.039823,spdsw,500,150,929,9,1,True,False
371,371,0.540741,0.303704,2.034236,spdsw,500,150,929,9,3,True,False
372,372,0.369004,0.247232,2.038062,spdsw,500,150,929,9,7,True,False
373,373,0.560606,0.375000,2.037453,spdsw,500,150,929,9,8,True,False
374,374,1.000000,1.000000,0.000000,spdsw,500,150,929,9,9,True,False

In [11]:
distances = results_subject["distance"].unique()
subjects_src = results_subject["subject"].unique()
subjects_tgt = results_subject["target_subject"].unique()

In [12]:
L_subject = {}
for distance in distances:
    L_subject[distance] = {}
L_subject["no_align"] = {}


for distance in distances:
    for s1 in subjects_src:
        L_subject[distance][s1] = {}
        for s2 in subjects_tgt:
            if s1 != s2:
                L_subject[distance][s1][s2] = {}
        
                scores = results_subject[
                    (results_subject["distance"] == distance)
                    & (results_subject["subject"] == s1)
                    & (results_subject["target_subject"] == s2)
                ]["align"]
                m_score = scores.mean()
                std_score = scores.std()
                
                times = results_subject[
                    (results_subject["distance"] == distance)
                    & (results_subject["subject"] == s1)
                    & (results_subject["target_subject"] == s2)
                ]["time"]
                
                m_t = times.mean()
                std_t = times.std()
                
                L_subject[distance][s1][s2]["mean_score"] = m_score
                L_subject[distance][s1][s2]["std_score"] = std_score
                L_subject[distance][s1][s2]["mean_time"] = m_t
                L_subject[distance][s1][s2]["std_t"] = std_t
        
        
for s1 in subjects_src:
    L_subject["no_align"][s1] = {}
    for s2 in subjects_tgt:
        if s1 != s2:
            dico_distances = {"mean_score": 0, "std_score": 0, "mean_time": 0, "std_time":0}

            scores = results_subject[
                (results_subject["distance"] == distance)
                & (results_subject["subject"] == s1)
                & (results_subject["target_subject"] == s2)
            ]["no_align"]
            m_score = scores.mean()
            std_score = scores.std()

            dico_distances["mean_score"] = m_score
            dico_distances["std_score"] = std_score

            L_subject["no_align"][s1][s2] = dico_distances

In [13]:
L_subject

{'lew': {1: {3: {'mean_score': 0.6555555555555556,
    'std_score': 0.0,
    'mean_time': 3.477886438369751,
    'std_t': 0.8137190667429272},
   7: {'mean_score': 0.4095940959409594,
    'std_score': 0.0,
    'mean_time': 3.117964506149292,
    'std_t': 0.018455848327926756},
   8: {'mean_score': 0.5606060606060606,
    'std_score': 0.0,
    'mean_time': 3.409115505218506,
    'std_t': 0.029413321200143817},
   9: {'mean_score': 0.3881856540084388,
    'std_score': 0.0,
    'mean_time': 3.470885467529297,
    'std_t': 0.023462107066123165}},
  3: {1: {'mean_score': 0.5494505494505495,
    'std_score': 0.0,
    'mean_time': 3.1336690902709963,
    'std_t': 0.011001196841093757},
   7: {'mean_score': 0.41697416974169743,
    'std_score': 6.206335383118183e-17,
    'mean_time': 4.229627275466919,
    'std_t': 0.00986355206215038},
   8: {'mean_score': 0.6174242424242424,
    'std_score': 0.0,
    'mean_time': 3.3066195487976073,
    'std_t': 0.014437542710143223},
   9: {'mean_score': 0.4751054852320674,
    'std_score': 0.00377395439240474,
    'mean_time': 3.392788791656494,
    'std_t': 0.01098238652982011}},
  7: {1: {'mean_score': 0.4761904761904761,
    'std_score': 0.0,
    'mean_time': 3.910536289215088,
    'std_t': 0.01112990252586381},
   3: {'mean_score': 0.4629629629629629,
    'std_score': 0.0,
    'mean_time': 3.023931884765625,
    'std_t': 0.022642221103364807},
   8: {'mean_score': 0.4015151515151515,
    'std_score': 0.0,
    'mean_time': 3.4621310234069824,
    'std_t': 0.031952026625015915},
   9: {'mean_score': 0.4438818565400844,
    'std_score': 0.003530211082422243,
    'mean_time': 3.4276308536529543,
    'std_t': 0.03488457265275328}},
  8: {1: {'mean_score': 0.4073260073260073,
    'std_score': 0.003064688741883043,
    'mean_time': 3.430191898345947,
    'std_t': 0.027385926617965302},
   3: {'mean_score': 0.4118518518518518,
    'std_score': 0.0016563466499998466,
    'mean_time': 3.2836443901062013,
    'std_t': 0.019982970132224404},
   7: {'mean_score': 0.2988929889298893,
    'std_score': 0.0,
    'mean_time': 3.509669542312622,
    'std_t': 0.02657031737711081},
   9: {'mean_score': 0.47172995780590715,
    'std_score': 0.001886977196202356,
    'mean_time': 3.0759772777557375,
    'std_t': 0.03266963368353782}},
  9: {1: {'mean_score': 0.3663003663003663,
    'std_score': 0.0,
    'mean_time': 3.506461191177368,
    'std_t': 0.033618379558372026},
   3: {'mean_score': 0.4148148148148148,
    'std_score': 0.0,
    'mean_time': 3.4196571826934816,
    'std_t': 0.015224281197511255},
   7: {'mean_score': 0.2619926199261992,
    'std_score': 0.0,
    'mean_time': 3.4585285663604735,
    'std_t': 0.004496467375796234},
   8: {'mean_score': 0.4424242424242424,
    'std_score': 0.00622411997164958,
    'mean_time': 3.1070910453796388,
    'std_t': 0.014053961914535878}}},
 'les': {1: {3: {'mean_score': 0.5896296296296297,
    'std_score': 0.0016563466499998217,
    'mean_time': 6.828950262069702,
    'std_t': 1.4681381154516577},
   7: {'mean_score': 0.5092250922509225,
    'std_score': 0.0,
    'mean_time': 7.363264751434326,
    'std_t': 1.4130663666781065},
   8: {'mean_score': 0.556060606060606,
    'std_score': 0.006775963568181209,
    'mean_time': 7.458433198928833,
    'std_t': 1.244563577843576},
   9: {'mean_score': 0.4151898734177215,
    'std_score': 0.003773954392404718,
    'mean_time': 9.010136795043945,
    'std_t': 1.1944184637903155}},
  3: {1: {'mean_score': 0.41025641025641024,
    'std_score': 0.00859050505462167,
    'mean_time': 6.97279109954834,
    'std_t': 1.1643690819914034},
   7: {'mean_score': 0.41697416974169743,
    'std_score': 6.206335383118183e-17,
    'mean_time': 5.634336042404175,
    'std_t': 0.3836099856493607},
   8: {'mean_score': 0.5613636363636364,
    'std_score': 0.010510937064781569,
    'mean_time': 7.392235898971558,
    'std_t': 1.1199203622261298},
   9: {'mean_score': 0.4995780590717301,
    'std_score': 0.003773954392404712,
    'mean_time': 9.976675224304199,
    'std_t': 1.1568986251219369}},
  7: {1: {'mean_score': 0.4175824175824176,
    'std_score': 0.0,
    'mean_time': 9.183534717559814,
    'std_t': 0.128325626577074},
   3: {'mean_score': 0.4659259259259259,
    'std_score': 0.0016563466499998714,
    'mean_time': 6.431302547454834,
    'std_t': 0.8976281689710436},
   8: {'mean_score': 0.3833333333333333,
    'std_score': 0.0016939908920452938,
    'mean_time': 6.215410614013672,
    'std_t': 1.7274338602618295},
   9: {'mean_score': 0.39746835443037964,
    'std_score': 0.0018869771962023807,
    'mean_time': 8.246352386474609,
    'std_t': 1.6852658164172565}},
  8: {1: {'mean_score': 0.38681318681318677,
    'std_score': 0.00665417660241207,
    'mean_time': 9.042930746078492,
    'std_t': 1.5341247294163465},
   3: {'mean_score': 0.4607407407407407,
    'std_score': 0.0033126932999997184,
    'mean_time': 8.37273292541504,
    'std_t': 0.4173360786395588},
   7: {'mean_score': 0.3808118081180812,
    'std_score': 0.015079569551072017,
    'mean_time': 5.964414644241333,
    'std_t': 1.385101903351811},
   9: {'mean_score': 0.49957805907173,
    'std_score': 0.012867468929938345,
    'mean_time': 9.112084102630615,
    'std_t': 1.2285420314382225}},
  9: {1: {'mean_score': 0.3326007326007326,
    'std_score': 0.016865735433291357,
    'mean_time': 7.905969762802124,
    'std_t': 1.140316716933072},
   3: {'mean_score': 0.4333333333333333,
    'std_score': 0.0,
    'mean_time': 7.153830862045288,
    'std_t': 1.5867383742857888},
   7: {'mean_score': 0.2568265682656826,
    'std_score': 0.012404233442045493,
    'mean_time': 5.889645195007324,
    'std_t': 0.9414816274267389},
   8: {'mean_score': 0.48636363636363633,
    'std_score': 0.013551927136362349,
    'mean_time': 7.611674737930298,
    'std_t': 1.3015157920063094}}},
 'spdsw': {1: {3: {'mean_score': 0.6511111111111111,
    'std_score': 0.006625386599999342,
    'mean_time': 2.133685350418091,
    'std_t': 0.005073127628944999},
   7: {'mean_score': 0.5055350553505535,
    'std_score': 0.011957086159424098,
    'mean_time': 2.120618486404419,
    'std_t': 0.007200023946266509},
   8: {'mean_score': 0.6492424242424242,
    'std_score': 0.015292900938019948,
    'mean_time': 2.1369200706481934,
    'std_t': 0.00842898312680337},
   9: {'mean_score': 0.49367088607594933,
    'std_score': 0.024054333862851045,
    'mean_time': 2.0938932418823244,
    'std_t': 0.00925788705951863}},
  3: {1: {'mean_score': 0.6058608058608059,
    'std_score': 0.010553011202115714,
    'mean_time': 2.1305098056793215,
    'std_t': 0.010360672663036457},
   7: {'mean_score': 0.5476014760147601,
    'std_score': 0.009622438974468867,
    'mean_time': 2.124468231201172,
    'std_t': 0.005038457050204131},
   8: {'mean_score': 0.6931818181818181,
    'std_score': 0.017358241268772143,
    'mean_time': 2.1295506954193115,
    'std_t': 0.010200083798945431},
   9: {'mean_score': 0.5578059071729958,
    'std_score': 0.01724288332633131,
    'mean_time': 2.0842180252075195,
    'std_t': 0.0072863766167377665}},
  7: {1: {'mean_score': 0.4307692307692307,
    'std_score': 0.00665417660241207,
    'mean_time': 2.127118158340454,
    'std_t': 0.008172044011904373},
   3: {'mean_score': 0.5059259259259259,
    'std_score': 0.020720889971406486,
    'mean_time': 2.131032657623291,
    'std_t': 0.008212706233139242},
   8: {'mean_score': 0.4492424242424242,
    'std_score': 0.011236664374387344,
    'mean_time': 2.1372241020202636,
    'std_t': 0.006099709763585289},
   9: {'mean_score': 0.44303797468354433,
    'std_score': 0.02651857613919098,
    'mean_time': 2.0853075981140137,
    'std_t': 0.009133931476384837}},
  8: {1: {'mean_score': 0.5684981684981685,
    'std_score': 0.035551899072676724,
    'mean_time': 2.1087803840637207,
    'std_t': 0.008180377666536632},
   3: {'mean_score': 0.6718518518518517,
    'std_score': 0.022160407854298625,
    'mean_time': 2.1174496173858643,
    'std_t': 0.0066411466013049335},
   7: {'mean_score': 0.44575645756457566,
    'std_score': 0.01315020640679372,
    'mean_time': 2.1082931041717528,
    'std_t': 0.008139401380724763},
   9: {'mean_score': 0.5637130801687763,
    'std_score': 0.014798040436076144,
    'mean_time': 2.067397356033325,
    'std_t': 0.010198560774787787}},
  9: {1: {'mean_score': 0.4564102564102563,
    'std_score': 0.03282427372486424,
    'mean_time': 2.0456613063812257,
    'std_t': 0.009572329927217968},
   3: {'mean_score': 0.5251851851851852,
    'std_score': 0.039056078004337996,
    'mean_time': 2.0348806858062742,
    'std_t': 0.006833024963136606},
   7: {'mean_score': 0.381549815498155,
    'std_score': 0.06782042886735146,
    'mean_time': 2.0374032497406005,
    'std_t': 0.007989233318750798},
   8: {'mean_score': 0.6060606060606061,
    'std_score': 0.02872301304564983,
    'mean_time': 2.042272663116455,
    'std_t': 0.0059609978666064056}}},
 'no_align': {1: {3: {'mean_score': 0.5074074074074074,
    'std_score': 0.0,
    'mean_time': 0,
    'std_time': 0},
   7: {'mean_score': 0.4206642066420664,
    'std_score': 0.0,
    'mean_time': 0,
    'std_time': 0},
   8: {'mean_score': 0.3560606060606061,
    'std_score': 0.0,
    'mean_time': 0,
    'std_time': 0},
   9: {'mean_score': 0.2616033755274262,
    'std_score': 0.0,
    'mean_time': 0,
    'std_time': 0}},
  3: {1: {'mean_score': 0.326007326007326,
    'std_score': 0.0,
    'mean_time': 0,
    'std_time': 0},
   7: {'mean_score': 0.3136531365313653,
    'std_score': 0.0,
    'mean_time': 0,
    'std_time': 0},
   8: {'mean_score': 0.4886363636363636,
    'std_score': 0.0,
    'mean_time': 0,
    'std_time': 0},
   9: {'mean_score': 0.2658227848101265,
    'std_score': 0.0,
    'mean_time': 0,
    'std_time': 0}},
  7: {1: {'mean_score': 0.42710622710622703,
    'std_score': 0.003276290076922751,
    'mean_time': 0,
    'std_time': 0},
   3: {'mean_score': 0.4066666666666666,
    'std_score': 0.0016563466499998466,
    'mean_time': 0,
    'std_time': 0},
   8: {'mean_score': 0.2613636363636363,
    'std_score': 0.0,
    'mean_time': 0,
    'std_time': 0},
   9: {'mean_score': 0.260759493670886,
    'std_score': 0.0018869771962023807,
    'mean_time': 0,
    'std_time': 0}},
  8: {1: {'mean_score': 0.4761904761904761,
    'std_score': 0.0,
    'mean_time': 0,
    'std_time': 0},
   3: {'mean_score': 0.5333333333333333,
    'std_score': 0.0,
    'mean_time': 0,
    'std_time': 0},
   7: {'mean_score': 0.2361623616236162,
    'std_score': 0.0,
    'mean_time': 0,
    'std_time': 0},
   9: {'mean_score': 0.350210970464135,
    'std_score': 0.0,
    'mean_time': 0,
    'std_time': 0}},
  9: {1: {'mean_score': 0.2549450549450549,
    'std_score': 0.0020063097344511813,
    'mean_time': 0,
    'std_time': 0},
   3: {'mean_score': 0.30740740740740746,
    'std_score': 0.003703703703703709,
    'mean_time': 0,
    'std_time': 0},
   7: {'mean_score': 0.24723247232472317,
    'std_score': 3.1031676915590914e-17,
    'mean_time': 0,
    'std_time': 0},
   8: {'mean_score': 0.3787878787878788,
    'std_score': 0.0037878787878787568,
    'mean_time': 0,
    'std_time': 0}}}}

In [14]:
results_mean = np.zeros((len(subjects_src), len(distances)+1))
t_subjects = np.zeros((len(subjects_src), len(distances)))

for l, distance in enumerate(L_subject):
    results = np.zeros((5,5))
    ts = np.zeros((5,5))
    for i, s1 in enumerate(subjects_src):
        for j, s2 in enumerate(subjects_tgt):
            if s1 != s2:
                results[i, j] = L_subject[distance][s1][s2]["mean_score"]
                if distance != "no_align":
                    ts[i, j] = L_subject[distance][s1][s2]["mean_time"]
                
        results_mean[i, l] = np.sum(results[i, :])/4
        
        if distance != "no_align":
            t_subjects[i, l] = np.sum(ts[i, :])/4
                       
    results_pd = pd.DataFrame(results, index=subjects_src, columns=subjects_tgt)
    print(distance)
    print(results_pd)
    print()

lew
          1         3         7         8         9
1  0.000000  0.655556  0.409594  0.560606  0.388186
3  0.549451  0.000000  0.416974  0.617424  0.475105
7  0.476190  0.462963  0.000000  0.401515  0.443882
8  0.407326  0.411852  0.298893  0.000000  0.471730
9  0.366300  0.414815  0.261993  0.442424  0.000000

les
          1         3         7         8         9
1  0.000000  0.589630  0.509225  0.556061  0.415190
3  0.410256  0.000000  0.416974  0.561364  0.499578
7  0.417582  0.465926  0.000000  0.383333  0.397468
8  0.386813  0.460741  0.380812  0.000000  0.499578
9  0.332601  0.433333  0.256827  0.486364  0.000000

spdsw
          1         3         7         8         9
1  0.000000  0.651111  0.505535  0.649242  0.493671
3  0.605861  0.000000  0.547601  0.693182  0.557806
7  0.430769  0.505926  0.000000  0.449242  0.443038
8  0.568498  0.671852  0.445756  0.000000  0.563713
9  0.456410  0.525185  0.381550  0.606061  0.000000

no_align
          1         3         7         8         9
1  0.000000  0.507407  0.420664  0.356061  0.261603
3  0.326007  0.000000  0.313653  0.488636  0.265823
7  0.427106  0.406667  0.000000  0.261364  0.260759
8  0.476190  0.533333  0.236162  0.000000  0.350211
9  0.254945  0.307407  0.247232  0.378788  0.000000

In [15]:
pd.DataFrame(results_mean, index=subjects_src, columns=np.concatenate([distances, ["no_align"]]))

        lew       les     spdsw  no_align
1  0.503485  0.517526  0.574890  0.386434
3  0.514739  0.472043  0.601113  0.348530
7  0.446138  0.416078  0.457244  0.338974
8  0.397450  0.431986  0.562455  0.398974
9  0.371383  0.377281  0.492301  0.297093

In [16]:
pd.DataFrame(t_subjects, index=subjects_src, columns=distances)

        lew       les     spdsw
1  3.368963  7.665196  2.121279
3  3.515676  7.494010  2.117187
7  3.456058  7.519150  2.120171
8  3.324871  8.123041  2.100480
9  3.372934  7.140280  2.040054